### ISSUE TITLE
respondToTrade method takes int for tradeId however tradeId's are now too large for int values

### ISSUE THREAD

**Issue by AaronSiems** [Longi94/JavaSteam#159]
I assume that tradeId is what the steam api getTradeOffers call returns as tradeofferid but if it's something else then maybe this is a non-issue.

Currently these numbers are in the 4 billions, a bit outside the 2 billion range of an int. I was going to try changing the data types to longs but I must be cloning the repo wrong or not building it right because I don't get the enum or prototype packages.

I'm using `https://api.steampowered.com/IEconService/GetTradeOffers/v1/?key=<key>&get_sent_offers=false&get_received_offers=true&get_descriptions=true&language=english&active_only=true&historical_only=false&time_historical_cutoff=0` to retrieve my trade offers and then sort those into ones I want to accept, which are then passed to the SteamTrading.respondToTrade method which can't work since the data types don't match. 

  - Version: 1.0.0-SNAPSHOT using Maven

**Comment by Longi94** [comment]
building the project should automatically generate the protos and enums. you can also try manually generating them with `./gradlew generateProto generateSteamLanguage`. They will be under `build/generated` and gradle (and IntelliJ) recognise that folder.

**Comment by AaronSiems** [comment]
Alright thanks, I was able to change it to longs but I realize now that this is dealing with the "invite to trade" type offers whereas I'm trying to deal with trade offers (and those id's might be different and still int range but I don't know nor care). There's nothing in here to accept those is there?
