### ISSUE TITLE
steamClient.connect does nothing

### ISSUE THREAD

**Issue by exellian** [Longi94/JavaSteam#3]
The first time the connect function worked. But after two starts it doesnt work anymore

**Comment by Longi94** [comment]
Please elaborate/share a code snippet. Is this after connecting disconnecting twice? Is there anything in the logs? How can I reproduce this issue?

**Comment by exellian** [comment]
#run method from Thread
`@Override
	public synchronized void run() {
		setup();
		print("Connecting...");
		steamClient.connect();
		while(running) {
			managerCB.runWaitCallbacks(1000L);
		}
	}`
#Setup function
`private void setup() {
		SteamConfigurationBuilder configBuilder = new SteamConfigurationBuilder();
		configBuilder.withServerListProvider(new FileServerListProvider(new File(SteamBotManager.getSteamserverspath())));
		
		steamClient = new SteamClient(configBuilder.build());
		
		managerCB = new CallbackManager(steamClient);
		
		steamUser = steamClient.getHandler(in.dragonbra.javasteam.steam.handlers.steamuser.SteamUser.class);
		friends = steamClient.getHandler(SteamFriends.class);
		//Own Handlers//
		apps = steamClient.getHandler(SteamUserApps.class);
		trading = steamClient.getHandler(SteamUserTrading.class);
		//End own Handlers//
		managerCB.subscribe(ConnectedCallback.class, this::onConnected);
        managerCB.subscribe(DisconnectedCallback.class, this::onDisconnected);

        managerCB.subscribe(LoggedOnCallback.class, this::onLoggedOn);
        managerCB.subscribe(LoggedOffCallback.class, this::onLoggedOff);
        
        managerCB.subscribe(UpdateMachineAuthCallback.class, this::onMachineAuth);
        managerCB.subscribe(LoginKeyCallback.class, this::onLoginKey);
        
        managerCB.subscribe(AccountInfoCallback.class, this::anAccountInfo);
        
        if(logOnOptions == null) {
        	logOnOptions = new LogOnDetails();
        	logOnOptions.setUsername(config.getUsername());
        	if(config.getLoginKey() != null) {
        		logOnOptions.setLoginKey(config.getLoginKey());
        	}else {
        		logOnOptions.setPassword(config.getPassword());
        	}
        	if(config.getAccountType() == Types.STEAM_GUARD_EMAIL_AUTHENTIFICATION) {
        		logOnOptions.setAuthCode(config.getSteamAuthCode());
        	}else if(config.getAccountType() == Types.STEAM_GUARD_MOBILE_AUTHENTIFICATOR) {
        		logOnOptions.setTwoFactorCode(config.getSteamTwoFactorCode());
        	}
        	logOnOptions.setShouldRememberPassword(true);
        	print(config.getSteamTwoFactorCode());
        }
        
	}`

But the onConnected Event gets not emitted!

**Comment by exellian** [comment]
`private void setup() {
		SteamConfigurationBuilder configBuilder = new SteamConfigurationBuilder();
		configBuilder.withServerListProvider(new FileServerListProvider(new File(SteamBotManager.getSteamserverspath())));
		
		steamClient = new SteamClient(configBuilder.build());
		
		managerCB = new CallbackManager(steamClient);
		
		steamUser = steamClient.getHandler(in.dragonbra.javasteam.steam.handlers.steamuser.SteamUser.class);
		friends = steamClient.getHandler(SteamFriends.class);
		//Own Handlers//
		apps = steamClient.getHandler(SteamUserApps.class);
		trading = steamClient.getHandler(SteamUserTrading.class);
		//End own Handlers//
		managerCB.subscribe(ConnectedCallback.class, this::onConnected);
        managerCB.subscribe(DisconnectedCallback.class, this::onDisconnected);

        managerCB.subscribe(LoggedOnCallback.class, this::onLoggedOn);
        managerCB.subscribe(LoggedOffCallback.class, this::onLoggedOff);
        
        managerCB.subscribe(UpdateMachineAuthCallback.class, this::onMachineAuth);
        managerCB.subscribe(LoginKeyCallback.class, this::onLoginKey);
        
        managerCB.subscribe(AccountInfoCallback.class, this::anAccountInfo);
        
        if(logOnOptions == null) {
        	logOnOptions = new LogOnDetails();
        	logOnOptions.setUsername(config.getUsername());
        	if(config.getLoginKey() != null) {
        		logOnOptions.setLoginKey(config.getLoginKey());
        	}else {
        		logOnOptions.setPassword(config.getPassword());
        	}
        	if(config.getAccountType() == Types.STEAM_GUARD_EMAIL_AUTHENTIFICATION) {
        		logOnOptions.setAuthCode(config.getSteamAuthCode());
        	}else if(config.getAccountType() == Types.STEAM_GUARD_MOBILE_AUTHENTIFICATOR) {
        		logOnOptions.setTwoFactorCode(config.getSteamTwoFactorCode());
        	}
        	logOnOptions.setShouldRememberPassword(true);
        	print(config.getSteamTwoFactorCode());
        }
        
	}`

**Comment by exellian** [comment]
But the onConnected event is not emitted

**Comment by Longi94** [comment]
Instead of using the `SteamConfigurationBuilder`, use the static `create` function of `SteamConfiguration` like this:

```java
SteamConfiguration configuration = SteamConfiguration.create(builder -> {
    builder.withServerListProvider(new FileServerListProvider(new File(SteamBotManager.getSteamserverspath())));
});
steamClient = new SteamClient(configuration);
```

If that doesn't work, see if there is anything in the logs.
```java
LogManager.addListener(new DefaultLogListener());
```

**Comment by exellian** [comment]
17:09:36.159 [  Thread-0] in.dragonbra.javasteam.steam.discovery.SmartCMServerList - Resolving server list
17:09:36.717 [  Thread-0] in.dragonbra.javasteam.steam.discovery.SmartCMServerList - Resolved 160 servers
17:09:36.732 [  Thread-0] in.dragonbra.javasteam.networking.steam3.TcpConnection - Connecting to /40.197.254.162:27017...
17:09:41.734 [  Thread-0] java.net.SocketTimeoutException: connect timed out
in.dragonbra.javasteam.networking.steam3.TcpConnection - Socket exception while completing connection request to /40.197.254.162:27017
17:09:41.734 [  Thread-0] in.dragonbra.javasteam.networking.steam3.TcpConnection - Timed out while connecting to /40.197.254.162:27017
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at in.dragonbra.javasteam.networking.steam3.TcpConnection.connect(TcpConnection.java:114)
	at in.dragonbra.javasteam.networking.steam3.EnvelopeEncryptedConnection.connect(EnvelopeEncryptedConnection.java:193)
	at in.dragonbra.javasteam.networking.steam3.Connection.connect(Connection.java:62)
	at in.dragonbra.javasteam.steam.CMClient.connect(CMClient.java:166)
	at in.dragonbra.javasteam.steam.CMClient.connect(CMClient.java:137)
	at steam.SteamUser.run(SteamUser.java:107)
	at java.lang.Thread.run(Unknown Source)
17:09:41.735 [  Thread-0] in.dragonbra.javasteam.steam.discovery.SmartCMServerList - Marking /40.197.254.162:27017 - TCP as BAD

**Comment by Longi94** [comment]
Looks like the IP it's trying to connect to isn't reachable. I've noticed it myself, that lately some of the servers returned by the steam directory are unreachable. The steam client will **NOT** try to reconnect automatically. You have to do that manually, you can do that in the disconnected callback.

**Comment by exellian** [comment]
reconnecting didn't work! I have to delete the servers.bin file every time, then it works without problems
